### ISSUE TITLE
Different Categories

### ISSUE THREAD

**Issue by hazycora** [GilgusMaximus/yt-trending-scraper#4]
Trending shows 4 categories for different types of content.
![image](https://user-images.githubusercontent.com/72580505/117478262-8cbfde00-af24-11eb-941e-d1fc554fd6c7.png)
It would be very useful if it was possible to get a specific category of trending.
Perhaps this could work like
```js
ytrend.scrape_trending_page('JP', true, 'music').then((data) =>{
    console.log(data);
}).catch((error)=>{
    console.log(error);
});
```
with the default category being 'now'.

**Comment by GilgusMaximus** [comment]
Okay cool.
I'll post the links to the categories in here, to check whether the links stay the same over multiple days and countries and then I'll implement the changes :)

Music: https://www.youtube.com/feed/trending?bp=4gINGgt5dG1hX2NoYXJ0cw%3D%3D
Gaming: https://www.youtube.com/feed/trending?bp=4gIcGhpnYW1pbmdfY29ycHVzX21vc3RfcG9wdWxhcg%3D%3D
Movies: https://www.youtube.com/feed/trending?bp=4gIKGgh0cmFpbGVycw%3D%3D

**Comment by GilgusMaximus** [comment]
So, I got around to implement this feature and it is fully available in the newest version on npm.
Please be aware that the API changed, in order to make it easier to pass the optional parameters to the library.

Best Regards,
Gilgus
